sonar.projectKey=RicardoCutipa_Fork_proyecto-si889-2026-i-u1-redsocialupt
sonar.organization=ricardocutipa
sonar.projectName=Red Social UPT

sonar.sources=auth-service/app,posts-service/app,profile-social-service/app,chat-service/app
sonar.tests=auth-service/tests,posts-service/tests,profile-social-service/tests,chat-service/tests

sonar.language=php
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/vendor/**,**/node_modules/**,**/storage/**
